# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
env:
  FIREBASE_TOKEN: secrets.FIREBASE_TOKEN
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: "16"
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Firebase tools
      - name: Install firebase
        run: npm install -g firebase-tools

      - name: Setup Firestore emulator
        run: firebase setup:emulators:firestore

      - name: Test
        run: npm run test:ci

      # Deploy step runs TSC compiler as pre-deploy
      - name: Build
        run: firebase deploy --only functions
